Repository onyx-lang/onyx, pull requests merged in 2023-12, with the labels that each got.

#36 Fixed: Windows compilation of `onyx_runtime.dll`
  build.bat
  runtime/src/ort_directories.h
Labels: bug

#53 Handle unary expressions when building array types; disallow negative array sizes; add test
  .gitignore
  compiler/src/astnodes.c
  compiler/src/types.c
  tests/bugs/array_lengths.onyx
Labels: bug, enhancement

#59 MacOS builds for OVM in GitHub Actions
  .github/workflows/onyx-build.yml
  interpreter/build.sh
  shared/lib/darwin_amd64/lib/libdyncall_s.a
  shared/lib/darwin_amd64/lib/libdyncallback_s.a
Labels: enhancement

#64 Support array programming with builtin operator overloads and new intrinsic
  compiler/include/astnodes.h
  compiler/include/wasm_emit.h
  compiler/src/builtins.c
  compiler/src/parser.c
  compiler/src/wasm_emit.c
  compiler/src/wasm_intrinsics.h
  core/alloc/heap.onyx
  core/builtin.onyx
  core/intrinsics/wasm.onyx
  core/operations.onyx
  scripts/run_tests.onyx
  tests/array_programming
  tests/array_programming.onyx
  tests/bugs/array_lengths
  tests/bugs/array_lengths.onyx
Labels: enhancement

#70 Fixed: GitHub actions build should exit if it fails
  build.sh
Labels: enhancement

#75 Fixed: Incorrect WASM binary generation when `void` type is in a compound type
  compiler/src/checker.c
  compiler/src/wasm_emit.c
Labels: bug

#78 Fixed: precedence of if-expressions
  compiler/src/parser.c
  tests/nested-if-exprs
  tests/nested-if-exprs.onyx
Labels: bug

#79 Fixed: nested array literals causes a segfault
  compiler/src/wasm_emit.c
  tests/nested_array_literals.onyx
  tests/nested_array_literals.txt
Labels: bug

#85 Support OVM debugging on mac
  compiler/src/wasm_runtime.c
  core/runtime/common.onyx
  core/threads/thread.onyx
  interpreter/include/ovm_debug.h
  interpreter/src/debug/debug_host.c
  interpreter/src/debug/debug_thread.c
  interpreter/src/vm/vm.c
  shared/lib/darwin_arm64/lib/libovmwasm.a
Labels: enhancement
