Repository onyx-lang/onyx, pull requests merged in 2025-01, with the labels that each got.

#180 fix indexing error in Array.insert
  core/container/array.onyx
Labels: bug

#181 Fix: Eliminate symres phase
  build.bat
  compiler/build.sh
  compiler/cli/main.c
  compiler/include/astnodes.h
  compiler/src/astnodes.c
  compiler/src/checker.c
  compiler/src/clone.c
  compiler/src/entities.c
  compiler/src/extensions.c
  compiler/src/library_main.c
  compiler/src/parser.c
  compiler/src/polymorph.h
  compiler/src/symres.c
  compiler/src/types.c
  compiler/src/utils.c
  core/net/net.onyx
  shared/include/onyx.h
Labels: enhancement, tech debt

#182 Experiment: For-loops as macro expansions
  compiler/include/astnodes.h
  compiler/src/astnodes.c
  compiler/src/builtins.c
  compiler/src/checker.c
  compiler/src/clone.c
  compiler/src/library_main.c
  compiler/src/parser.c
  compiler/src/polymorph.h
  compiler/src/utils.c
  compiler/src/wasm_emit.c
  compiler/src/wasm_runtime.c
  core/builtin.onyx
  core/container/iter.onyx
  core/container/map.onyx
  core/container/set.onyx
  core/operations.onyx
  tests/aoc-2021/day11.onyx
  tests/for_expansion_misc
  tests/for_expansion_misc.onyx
  tests/remove_test
  tests/remove_test.onyx
Labels: enhancement
